version: '2'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - volume:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    ports:
      -"80:80"
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

networks:
  site:
volumes:
  volume: